export const projects = [
  {
    slug: "atlas",
    title: "Atlas",
    subtitle: "Travel Planning Platform",
    category: "Web Development · AI Integration",
    year: "2025",
    description:
      "Next-generation travel platform integrating interactive maps, smart search, and real-time AI-powered recommendations.",
    tech: [
      "React 19",
      "Vite",
      "Tailwind CSS",
      "Spring Boot",
      "PostgreSQL",
      "Supabase",
      "Groq AI",
    ],
    image: "/imgs/mockupAtlas.jpeg",
    links: { live: "#", repo: "#" },
    color: "#4f46e5",
  },
  {
    slug: "novavice",
    title: "NovaVice",
    subtitle: "Architecture Firm Website",
    category: "Web Development",
    year: "2025",
    description:
      "Architecture firm website where motion is the core experience. Seamless GSAP animations create an immersive exploration.",
    tech: ["HTML", "CSS", "JavaScript", "GSAP"],
    image: "/imgs/mockupNovaVice.png",
    links: { live: "#", repo: "#" },
    color: "#7c3aed",
  },
  {
    slug: "awwwards",
    title: "Awwwards",
    subtitle: "Interactive Universe",
    category: "Web Development",
    year: "2024",
    description:
      "Immersive universe with rich product array in interconnected overlay experience. Advanced GSAP animations and video integration.",
    tech: ["React", "GSAP", "Video"],
    image: "/imgs/mockupAwwwards.png",
    links: { live: "#", repo: "#" },
    color: "#2563eb",
  },
  {
    slug: "sacith",
    title: "Sacith",
    subtitle: "Product Catalog",
    category: "Web Development · SEO",
    year: "2024–2025",
    description:
      "Modern bilingual product catalog for Italian air-massage systems company. Full SEO optimization with Google Analytics integration.",
    tech: ["PHP", "MySQL", "JavaScript", "Tailwind CSS"],
    image: "/imgs/mockupSacith.png",
    links: { live: "#" },
    color: "#059669",
  },
  {
    slug: "japan",
    title: "Japan",
    subtitle: "Web Design Concept",
    category: "Web Design",
    year: "2025",
    description:
      "Web design celebrating Japan's beauty with minimalist layout, deep red tones, and neutral accents. Figma design project.",
    tech: ["Figma"],
    image: "/imgs/mockupJapan.png",
    links: { design: "#" },
    color: "#dc2626",
  },
  {
    slug: "sacith-lab",
    title: "Sacith Lab",
    subtitle: "Luxury Product Showcase",
    category: "Web Development",
    year: "2025",
    description:
      "High-end bilingual product showcase for a patented luxury stool. Built with HTML, PHP and Tailwind CSS.",
    tech: ["HTML", "PHP", "Tailwind CSS", "Figma"],
    image: "/imgs/mockupSacithLab.svg",
    links: { live: "#" },
    color: "#d97706",
  },
  {
    slug: "auth-app",
    title: "Auth App",
    subtitle: "Flutter Authentication",
    category: "App Development",
    year: "2024",
    description:
      "Powerful modern authentication system with Flutter and Firebase. Supports email/password and OAuth login.",
    tech: ["Flutter", "Firebase", "Google OAuth", "Apple OAuth"],
    image: "/imgs/mockupAuth.png",
    links: { repo: "#" },
    color: "#0891b2",
  },
  {
    slug: "film-app",
    title: "Film App",
    subtitle: "TMDB-Powered Discovery",
    category: "App Development",
    year: "2024",
    description:
      "Flutter app leveraging TMDB API for film discovery. Browse trending movies, search, and save favorites.",
    tech: ["Flutter", "TMDB API", "Dart"],
    image: "/imgs/mockupMovie.png",
    links: { repo: "#" },
    color: "#7c3aed",
  },
];

export const services = [
  {
    icon: "💻",
    title: "Software Developing",
    subtitle: "Full Stack",
    description:
      "Bring your vision to life. I collaborate to develop websites that truly represent your unique identity and style — from database to UI.",
    tech: ["React", "Next.js", "Node.js", "TypeScript", "Java Spring Boot"],
  },
  {
    icon: "✦",
    title: "UI/UX Design",
    subtitle: "Design Systems",
    description:
      "Craft your online presence. I design websites that not only look stunning but also tell your story with clarity and elegance.",
    tech: ["Figma", "Tailwind CSS", "GSAP", "Framer Motion"],
  },
  {
    icon: "◈",
    title: "AI Integration",
    subtitle: "Smart Solutions",
    description:
      "Smart solutions for modern needs. I integrate AI into your product to enhance user experience and streamline operations.",
    tech: ["OpenAI", "Groq", "Pinecone", "LangChain"],
  },
];

export const skills = {
  Frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Tailwind CSS",
    "SASS",
    "GSAP",
    "Framer Motion",
    "Redux",
    "React Query",
    "Bootstrap",
    "Material UI",
    "Zod",
    "Jest",
    "React Testing Library",
  ],
  Backend: [
    "Java Spring Boot",
    "Node.js",
    "Express.js",
    "PHP",
    "REST APIs",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Firebase",
    "Python",
  ],
  "Tools & Platforms": [
    "Figma",
    "Git",
    "GitHub",
    "Bitbucket",
    "Docker",
    "Vercel",
    "Supabase",
    "Firebase",
    "Postman",
    "Google Analytics",
    "Google Tag Manager",
  ],
};

export const experience = [
  {
    role: "Frontend Developer",
    company: "Contactlab (TeamSystem Group)",
    location: "Milan",
    period: "March 2026 — Present",
    tech: ["React", "TypeScript", "Functional Programming"],
    bullets: [
      "Design and implementation of frontend features for Contactlab CDP platform",
      "Functional programming approach with React and TypeScript",
      "Collaboration with product and backend teams",
    ],
  },
  {
    role: "Founding Software Engineer",
    company: "Newmann",
    location: "Remote",
    period: "November 2025 — Present",
    tech: [
      "Next.js",
      "TypeScript",
      "Java Spring Boot",
      "PostHog",
      "GCP",
      "OpenAI",
      "Pinecone",
      "Azure",
    ],
    bullets: [
      "Led development of MVP for AI-powered email automation platform",
      "Integrated Google and Microsoft OAuth for seamless user onboarding",
      "Implemented core functionalities including AI-driven classification and response generation",
      "Set up analytics and monitoring with PostHog to track user interactions and system performance",
    ],
  },
  {
    role: "Junior Developer",
    company: "HRM Group",
    location: "Milan",
    period: "November 2024 — March 2026",
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Java Spring Boot",
      "Figma",
    ],
    bullets: [
      "Ownership of front-end development of main project from scratch with Next.js",
      "Implemented back-end features using Java Spring Boot",
      "Mentored a junior intern and contributed to two additional projects",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "Sacith srl",
    location: "Cassano Magnago",
    period: "Feb 2025 — March 2025",
    tech: ["PHP", "JavaScript", "SQL", "SEO", "Google Analytics"],
    bullets: [
      "Led end-to-end development of showcase website and digital product catalog",
      "Applied SEO best practices and maintained continuous client engagement",
      "Integrated Google Analytics for performance tracking and insights",
    ],
  },
];
