import type { Metadata } from "next";
import { defaultLocale, locales, type Locale } from "./config";
import { siteUrl } from "@/site";

/**
 * Canonical and hreflang links for one page.
 * `route` is the path after the locale segment, e.g. "/projects" ("" for the home page).
 */
export function alternates(lang: Locale, route = "") {
  return {
    canonical: `/${lang}${route}`,
    languages: {
      ...Object.fromEntries(locales.map((l) => [l, `/${l}${route}`])),
      "x-default": `/${defaultLocale}${route}`,
    },
  };
}

/** Facebook's locale format ("it_IT", "en_US"), used by OpenGraph. */
const OG_LOCALE: Record<Locale, string> = {
  it: "it_IT",
  en: "en_US",
};

/**
 * Full per-page metadata: canonical + hreflang + OpenGraph + Twitter card,
 * generated together so a page only decides its own title and description.
 *
 * OpenGraph and Twitter must be set on every page because Next.js replaces
 * (does not merge) nested metadata fields when a page overrides the layout —
 * so sharing this from one helper is how the two stay in sync per URL.
 */
export function pageMetadata({
  lang,
  route = "",
  title,
  description,
  images,
}: {
  lang: Locale;
  route?: string;
  title: string;
  description: string;
  /**
   * Override images for this page (case studies use their hero). When omitted,
   * Next.js's file-based convention auto-injects the site-wide OG image
   * generated by `[lang]/opengraph-image.tsx`.
   */
  images?: string[];
}): Metadata {
  const url = new URL(`/${lang}${route}`, siteUrl).toString();
  const ogImages = images?.map((src) => ({
    url: new URL(src, siteUrl).toString(),
  }));

  return {
    title,
    description,
    alternates: alternates(lang, route),
    openGraph: {
      title,
      description,
      url,
      siteName: "Luisa Cerin Ogbeiwi",
      locale: OG_LOCALE[lang],
      alternateLocale: locales
        .filter((l) => l !== lang)
        .map((l) => OG_LOCALE[l]),
      type: "website",
      ...(ogImages ? { images: ogImages } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      ...(ogImages ? { images: ogImages.map((i) => i.url) } : {}),
    },
  };
}
